### ISSUE TITLE
Wondertrade bot not properly selecting boxes in the last row

### ISSUE THREAD

**Issue by danne2** [drgoku282/PKMN-NTR#39] opened 2016-12-08 03:42 UTC
Sorry about opening and closing so many issues. I think I've finally debugged the issue. It appears that when you reach the last row of boxes, the bot fails to select the box. Earlier rows are fine, but that last row of boxes isn't properly selected. If you've already selected the box it can go through them, but if it has to select the box on its own it has issues selecting them.

**Comment by drgoku282** [comment] 2016-12-08 22:17
It seems a duplicate of #36, will try to reproduce the issue.

**Comment by danne2** [comment] 2016-12-08 22:18
Literally just reproduced it and am submitting a pull request with a fix. Positions were wrong.

**Closed by drgoku282** 2016-12-08 22:17 UTC
Labels: duplicate
