### ISSUE TITLE
Link a twitch bot to the software?

### ISSUE THREAD

**Issue by FreeSpirit87** [drgoku282/PKMN-NTR#124] opened 2017-12-11 15:07 UTC
Hello drgoku282

I was using ur program and was wondering if there are ny ways to add support for a twitch bot to it? I use this program during my afk hours to wondertrade on stream, and I would love to have some sort of countdown in my chat for when a pokemon is sent out. Is this possible and if so, can u enlighten me how?

**Comment by Loadie** [comment] 2017-12-11 15:13
You simply connect to Twitch like you would a mIRC client. There's plenty of documentation on how to connect and send chat messages on Twitch via C#. You can even look up a library, TwitchLib, and weave that into this project if you really want to.

**Comment by drgoku282** [comment] 2017-12-16 18:40
IIRC @EverOddish was the person who developed some Twitch support. I can't really help you because I don't know too much about this.

**Comment by EverOddish** [comment] 2017-12-20 14:16
I just added code to execute separate programs, nothing specific to Twitch. Loadie is correct though, you can easily connect to Twitch chat with any IRC client library.

**Comment by drgoku282** [comment] 2017-12-23 03:29
Since this issue is not a bug and an answer has been given I will close this.

**Closed by drgoku282** 2017-12-23 03:29 UTC
Labels: othercomponents, question
