### ISSUE TITLE
Wondertrade bot literally dead after latest Luma.

### ISSUE THREAD

**Issue by mmands994** [drgoku282/PKMN-NTR#99] opened 2017-07-07 14:38 UTC
It just doesn't work anymore. It's broken. It's dead.

Rest in pieces.

**Comment by Retrosol** [comment] 2017-07-14 17:43
Wonder Trade Bot works fine hit me up on discord @Retrosol#3697 I will give you a hand.

**Comment by drgoku282** [comment] 2017-07-15 19:24
Duplicate of #87 it seems. All discussion of latest Luma connection issues will be done there.

**Closed by drgoku282** 2017-07-15 19:24 UTC
Labels: duplicate
