### ISSUE TITLE
Remote Control not functioning on NTR 3.5

### ISSUE THREAD

**Issue by SerraraFluttershy** [drgoku282/PKMN-NTR#97] opened 2017-06-24 19:42 UTC
PKMN-NTR is able to do literally everything else other than this, Even if I use Luma3DS' new module, Rosalina, and enable InputRedirection it still won't accept the button inputs sent through this program...

Could there be an incompatibility with the most recent iteration of NTR?

**Comment by AlexL29** [comment] 2017-06-30 00:27
Try using InputRedirection the cia after enabling BootNTR, it worked for me.

**Comment by SerraraFluttershy** [comment] 2017-06-30 04:15
Alpha Sapphire is now refusing to connect to the internet when NTR is enabled, reporting an error...but I was able to use NTR online not even a week ago.

However, enabling InputRedirection then gives a _communication error_ which breaks online features entirely, and **this** message appears the moment the save file is loaded.


This is utter bull; I should be able to force Alpha Sapphire into going online with Rosalina but can't.
It's a problem that happens off and on on almost every version of NTR I've used in the past with ORAS

![bot_0002](https://user-images.githubusercontent.com/23690950/27720713-ce2e3ce2-5d20-11e7-8da3-387bd93729c9.jpeg)
![top_0002](https://user-images.githubusercontent.com/23690950/27720712-ce2c6142-5d20-11e7-9681-b780f588566f.jpeg)


 and I can't figure out what causes it....could TuxSH and Aurora look into this?

**Comment by AlexL29** [comment] 2017-06-30 12:47
My ORAS save works just fine with PKMN NTR and the wonder trade bot. Ignore the communication failed, and restart your 3DS. Then, open NTR 3.5, InputRedirection, and the Rosalina debugger, connect to internet in ORAS, and start PKMN NTR with your IP address.

**Comment by SerraraFluttershy** [comment] 2017-06-30 19:29
@AlexL29 
ORAS still refuses to let me go online, despite doing what you said exactly.

However, PKMN NTR *does* work, as I am able to view my party stats...but the Remote Control function does not.

I still assert that this is an issue with Rosalina/NTR and not my save file since normal functionality occured just over a week ago before this started to happen.

**Comment by SerraraFluttershy** [comment] 2017-07-09 22:21
I resolved the issue of not being online: it was due to a game plugin.
Even after removing the folder and doing your recommendation again, it still does not function with wireless input.

**Comment by drgoku282** [comment] 2017-07-15 19:26
Duplicate of #87, it seems.

**Closed by drgoku282** 2017-07-15 19:26 UTC
