### ISSUE TITLE
PKMN-NTR is not connecting o2ds IP

### ISSUE THREAD

**Issue by Gumzone** [drgoku282/PKMN-NTR#143] opened 2018-02-04 15:56 UTC
I have a o2ds and i launched ntr mode 3 then i went to the game and enabled the debbuger and I went online i inserted correctly the IP in pc but it s not connecting. What am I doing wrong? Note: I just want to use the breed bot in Ultra Moon

**Comment by Naturally-Delicious** [comment] 2018-02-05 02:44
You have to install InputRedirection mode3 and use that in conjunction with NTR mode 3. 

https://github.com/Stary2001/InputRedirection/releases

Download ` InputRedirection_mode3.cia` Always use newest version.

**Comment by Gumzone** [comment] 2018-02-05 07:57
So after the ntr mode 3 i go to the input redirectiom mode 3 then open the game enable the debugger  go online and connect with IP to computer? Is it needed inputredirection in pc or other files in the sd card?

**Comment by Naturally-Delicious** [comment] 2018-02-06 03:13
yes

no

**Comment by Gumzone** [comment] 2018-02-06 08:02
I got it work. The only problem is that some times the app stops and say that new.system was deleted and to get it work back i reinstall it and then works for a little mor and again new.system deletes

**Comment by Naturally-Delicious** [comment] 2018-02-07 03:55
show error message if there is any and what it says in log. an expert will come over and help u

**Comment by drgoku282** [comment] 2018-03-03 19:53
Seems a duplicate of #114, will mark this a such. Sadly my 2DS died and I don't have an old system to test.

**Closed by drgoku282** 2018-03-03 19:53 UTC
Labels: duplicate
