### ISSUE TITLE
Dragging a shiny Pokemon from PKHeX to PKMN-NTR changes it to non-shiny.

### ISSUE THREAD

**Issue by Naturally-Delicious** [drgoku282/PKMN-NTR#129] opened 2017-12-22 03:17 UTC
Please fix when you have time!! Your work is very appreciated :)

**Comment by drgoku282** [comment] 2017-12-23 03:37
It seems a possible duplicate of #126 does exporting the pokemon as a .pkx file from PKHeX and importing it again on PKMN ntr work correctly?

**Comment by Naturally-Delicious** [comment] 2018-01-01 18:26
Yes.

**Comment by drgoku282** [comment] 2018-01-06 21:37
Will mark this as a duplicate of #126 and close this issue. Anything related to this bug will be discussed there.

**Closed by drgoku282** 2018-01-06 21:37 UTC
Labels: bug, duplicate
