### ISSUE TITLE
new version 2.0.0-RC1 makes my system crash

### ISSUE THREAD

**Issue by Liger0** [drgoku282/PKMN-NTR#46] opened 2016-12-16 14:51 UTC
Hi, I don't know what changed in this version, but when I try to open it, my system just crashes.
**Edit:** After 20 resets of the computer and waiting an hour on the last session, the program opened and now it opens instantly. As yesterday my PC installed updated for windows 10 maybe there was something incompatible with the program, as the problem was only with this program (I also found out it gave me the same error on older versions).

**Comment by Liger0** [comment] 2016-12-16 19:33
So, i want to signale 2 new bugs.
1. After 111 resets, the console powered off the screens without any text (with old releases there was a text on the botton screen). Then, restarting the program and the console, the Bot make me receive all the events, and not just the first event.
2. Some hours later, I tried again to reset, and after the first reset it didn't talk the the lady. After I pressed A to tolk her, all started without any interruption.

**Comment by drgoku282** [comment] 2016-12-17 20:47
About the program crash, I use Windows 10, no problems on my end.

Are the problems still present, or they just happened once?

**Comment by Liger0** [comment] 2016-12-17 21:17
The bug that keeps me stop resetting with the text "finished successfully" persists after just some resets (may it be a problem if I keep a stat >=31 and not just =31 for a mistake?), and many times it just stops in front of the lady or just after it resets, letting me stuck into the intro.
Same obviously for the black screen, but I don't know if both the crashes (with a text on the bottom screen and without anything) are related to NTR itself.

**Comment by drgoku282** [comment] 2016-12-17 21:34
Is in Gen 6 or Gen 7? The gen 6 soft-reset bug was already reported. In gen 7 can't reproduce, it is working fine for me, either case it seems to be lag in your connection. Can you write the steps to reproduce the problem?

I've never heard of a black screen crash with text in the bottom screen. The one without text is already known, It is caused by NTR I can't do anything to solve it.

**Comment by Real96** [comment] 2016-12-17 23:07
He is talking about gen 6 bot, not gen 7.

For the black screen crash with text in the bottom screen: it is the same as the black screen bug caused by ntr.

**Comment by drgoku282** [comment] 2016-12-17 23:22
If it is gen 6 it was solved on a recent commit. For now I'll mark it as duplicate of #45

**Comment by Real96** [comment] 2016-12-17 23:41
Also this error: "The bug that keeps me stop resetting with the text "finished successfully" persists after just some resets (may it be a problem if I keep a stat >=31 and not just =31 for a mistake?), and many times it just stops in front of the lady or just after it resets, letting me stuck into the intro."?

**Comment by drgoku282** [comment] 2016-12-18 02:48
I didn't get that one.

Liger0, try with latest version.

**Comment by Liger0** [comment] 2016-12-18 15:39
So i tried. Before talking to the girl, at reset n.80, the program said: "An error has ocurred while reading data from your 3ds ram, please check connection and try again".

**Comment by drgoku282** [comment] 2016-12-18 17:49
For the first error, do you have the log? It just could be some lag in your 3DS connection.

For the second one it's an error in NTR, can't do anything about it.

**Comment by Liger0** [comment] 2016-12-18 18:42
Here it is the log. [](http://pastebin.com/tDyRVZ0s)

Anyway averytime I click the connect button, it opens up Onedrive on the PC (it is setted to not open when I start windows 10), can I do something as you know?

**Comment by drgoku282** [comment] 2016-12-18 18:54
I don't know why it tries to open OneDrive, there's nothing on the code that opens an external application, except for update checking, but it is done as soon the program is started and as your program is up to date, it doesn't do anything. Can't do anything about it, nobody else has reported such problem.

About the log, the problem is caused by lag in your 3DS, the soft-reset took too much time, I thought this problem was solved, I'll try something else for next release.

**Closed** 2016-12-18 18:58 UTC
Labels: bug, duplicate
